In [3]:
import pandas as pd 
import numpy as np

df=pd.read_csv(r"C:\Users\haith\Downloads\dirty_cafe_sales.csv")
df.head(100)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
95,TXN_8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20
96,TXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10
97,TXN_3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15
98,TXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27
99,TXN_8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [5]:
df['Quantity']=pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'], errors='coerce')
df["Total Spent"]=pd.to_numeric(df["Total Spent"], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [6]:
df["Quantity"].fillna(df['Total Spent']/df['Price Per Unit'],inplace=True)
df["Price Per Unit"].fillna(df['Total Spent']/df['Quantity'],inplace=True)
df["Total Spent"].fillna(df['Quantity']*df['Price Per Unit'],inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9962 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

C:\Users\haith\AppData\Local\Temp\ipykernel_26412\228390852.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(df['Total Spent']/df['Price Per Unit'],inplace=True)
C:\Users\haith\AppData\Local\Temp\ipykernel_26412\228390852.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price Per Unit"].fillna(df['Total Spent']/df['Quantity'],inplace=True)
C:\Users\haith\AppData\Local\Temp\ipykernel_26412\228390852.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total Spent"].fillna(df['Quantity']*df['Price Per Unit'],inplace=True)

In [7]:
df['Item'].value_counts()

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [8]:
df['Item'].replace(['UNKNOWN','ERROR'] , np.nan,inplace=True)
df.groupby('Item')['Price Per Unit'].unique()

C:\Users\haith\AppData\Local\Temp\ipykernel_26412\610874376.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Item'].replace(['UNKNOWN','ERROR'] , np.nan,inplace=True)

Item
Cake        [3.0, nan]
Coffee      [2.0, nan]
Cookie      [1.0, nan]
Juice       [3.0, nan]
Salad       [5.0, nan]
Sandwich    [4.0, nan]
Smoothie    [4.0, nan]
Tea         [1.5, nan]
Name: Price Per Unit, dtype: object

In [9]:
pd.isna(df['Item']).sum()

np.int64(969)

In [10]:
price_dictinary = {
    2.0: 'Coffee',
    1.0: 'Cookie',
    5.0: 'Salad',
    1.5: 'Tea'
}
df['Item']=df.apply(lambda x:price_dictinary[x['Price Per Unit']] if (pd.isna(x['Item'])) and (x["Price Per Unit"]) in price_dictinary else x['Item'], axis=1)
df['Item'].value_counts()

Item
Coffee      1291
Salad       1272
Cookie      1213
Tea         1207
Juice       1171
Cake        1139
Sandwich    1131
Smoothie    1096
Name: count, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9520 non-null   object
 2   Quantity          9962 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [18]:
df['Price Per Unit']=df['Price Per Unit'].fillna(df['Price Per Unit'].mean())   
df['Total Spent']=df['Total Spent'].fillna(df['Total Spent'].mean())
df['Quantity']=df['Quantity'].fillna(df['Total Spent']/df['Price Per Unit'])
df['Transaction Date']=pd.to_datetime(df['Transaction Date'],errors='coerce')
df.replace(['UNKNOWN','ERROR'], np.nan, inplace=True)
df[['Item', 'Payment Method', 'Transaction Date','Location']] = df[['Item', 'Payment Method', 'Transaction Date','Location']].fillna('UNKNOWN')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [21]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08 00:00:00
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16 00:00:00
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19 00:00:00
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27 00:00:00
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11 00:00:00
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,UNKNOWN,UNKNOWN,2023-08-30 00:00:00
9996,TXN_9659401,Cookie,3.0,1.0,3.0,Digital Wallet,UNKNOWN,2023-06-02 00:00:00
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,UNKNOWN,2023-03-02 00:00:00
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,UNKNOWN,2023-12-02 00:00:00
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07 00:00:00

In [22]:
df.to_csv(r"C:\Users\haith\Downloads\cleaned_cafe_sales.csv", index=False)