Libraries

In [4]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import pandas as pd

Variables

In [5]:
NumPage = 0
job_title = []
company_name = []
location_name = []
status = []
skills = []
links = []

Processing & Scarping

In [ ]:

while NumPage < 10:
    url = f"https://wuzzuf.net/search/jobs/?a=hpb%7Cspbg&q=python&start={NumPage}"
    try:
        # client = urlopen(url)
        # html = client.read()
        # client.close()
        responds = requests.get(url)
        html = responds.content
    except:
        break

    soup = BeautifulSoup(html, 'html.parser')

    job_titles = soup.find_all('h2', {'class': 'css-m604qf'})
    company_names = soup.find_all('a', {'class': 'css-17s97q8'})
    location_names = soup.find_all('span', {'class': 'css-5wys0k'})
    job_statuses = soup.find_all('div', {'class': 'css-1lh32fc'})
    job_skills = soup.find_all('div', {'class': 'css-y4udm8'})

    min_length = min(len(job_titles), len(company_names), len(location_names), len(job_statuses), len(job_skills))
    
    for i in range(min_length):
        job_title.append(job_titles[i].text.strip())
        links.append(job_titles[i].find('a').attrs['href'])
        company_name.append(company_names[i].text.strip())
        location_name.append(location_names[i].text.strip())
        status.append(job_statuses[i].text.strip())
        skills.append(job_skills[i].text.strip())

    NumPage += 1

,Job Title,Company Name,Location,Status,Skills Requirements,Links
0,Python Developer,Boca Pro -,"Maadi, Cairo, Egypt",Full TimeHybrid,Full TimeHybridExperienced · 4 - 7 Yrs of Exp ...,https://wuzzuf.net/jobs/p/tlwvmv5vjrvq-python-...
1,Data Entry (With Python Automation Experience),Confidential -,"Madina, Saudi Arabia",Full TimeRemote,Full TimeRemoteEntry Level · 1 - 2 Yrs of Exp ...,https://wuzzuf.net/jobs/p/bouqsly4isqd-data-en...
2,Python (Django) Developer,Teqneia -,"Sheikh Zayed, Giza, Egypt",Full TimeOn-site,Full TimeOn-siteEntry Level · 1 - 3 Yrs of Exp...,https://wuzzuf.net/jobs/p/ddbfgv871jlo-python-...
3,Senior Python AI Developer,Vigtas -,"Cairo, Egypt",Full TimeOn-site,Full TimeOn-siteExperienced · 3 - 8 Yrs of Exp...,https://wuzzuf.net/jobs/p/vab6snsugoi6-senior-...
4,Backend Engineer (Python) - EdTech Startup,Darsel -,"Cairo, Egypt",Full TimeRemote,Full TimeRemoteExperienced · 5+ Yrs of Exp · I...,https://wuzzuf.net/jobs/p/ivmknt2i3nip-backend...
...,...,...,...,...,...,...
130,Backend developer,Net2Source Inc. -,"Dubai, United Arab Emirates",Full Time,Full TimeEntry Level · Creative/Design/Art · I...,https://wuzzuf.net/jobs/p/g/fz0g8epznl2i-backe...
131,Systems Integrations Engineering Manager,Canonical -,"Riyadh, Saudi Arabia",Full Time,Full TimeExperienced · Installation/Maintenanc...,https://wuzzuf.net/jobs/p/g/kouxlxzfk2we-syste...
132,Financial Data Analyst,Etihad Airport Services -,"Dubai, United Arab Emirates",Full Time,Full TimeExperienced · Accounting/Finance · IT...,https://wuzzuf.net/jobs/p/g/jrvthu7qjoom-finan...
133,Trainee,Space42 -,"Dubai, United Arab Emirates",Full Time,Full TimeStudent · Accounting/Finance · Admini...,https://wuzzuf.net/jobs/p/g/zujy7cmgpqsi-train...
134,Security Engineer - Ubuntu,Canonical -,"Makkah, Saudi Arabia",Full Time,Full TimeEntry Level · Installation/Maintenanc...,https://wuzzuf.net/jobs/p/g/fhtjyqyuh4it-secur...

Storing

In [7]:
job_detail = {
    'Job Title': job_title,
    'Company Name': company_name,
    'Location': location_name,
    'Status': status,
    'Skills Requirements': skills,
    'Links': links
}

Convert to Excel File

In [8]:
df = pd.DataFrame(job_detail)
df
# df.to_excel('Wuzzuf Python Jobs Opportunity.xlsx' , index = False)

,Job Title,Company Name,Location,Status,Skills Requirements,Links
0,Python Developer,Boca Pro -,"Maadi, Cairo, Egypt",Full TimeHybrid,Full TimeHybridExperienced · 4 - 7 Yrs of Exp ...,https://wuzzuf.net/jobs/p/tlwvmv5vjrvq-python-...
1,Data Entry (With Python Automation Experience),Confidential -,"Madina, Saudi Arabia",Full TimeRemote,Full TimeRemoteEntry Level · 1 - 2 Yrs of Exp ...,https://wuzzuf.net/jobs/p/bouqsly4isqd-data-en...
2,Python (Django) Developer,Teqneia -,"Sheikh Zayed, Giza, Egypt",Full TimeOn-site,Full TimeOn-siteEntry Level · 1 - 3 Yrs of Exp...,https://wuzzuf.net/jobs/p/ddbfgv871jlo-python-...
3,Senior Python AI Developer,Vigtas -,"Cairo, Egypt",Full TimeOn-site,Full TimeOn-siteExperienced · 3 - 8 Yrs of Exp...,https://wuzzuf.net/jobs/p/vab6snsugoi6-senior-...
4,Backend Engineer (Python) - EdTech Startup,Darsel -,"Cairo, Egypt",Full TimeRemote,Full TimeRemoteExperienced · 5+ Yrs of Exp · I...,https://wuzzuf.net/jobs/p/ivmknt2i3nip-backend...
...,...,...,...,...,...,...
130,Backend developer,Net2Source Inc. -,"Dubai, United Arab Emirates",Full Time,Full TimeEntry Level · Creative/Design/Art · I...,https://wuzzuf.net/jobs/p/g/fz0g8epznl2i-backe...
131,Systems Integrations Engineering Manager,Canonical -,"Riyadh, Saudi Arabia",Full Time,Full TimeExperienced · Installation/Maintenanc...,https://wuzzuf.net/jobs/p/g/kouxlxzfk2we-syste...
132,Financial Data Analyst,Etihad Airport Services -,"Dubai, United Arab Emirates",Full Time,Full TimeExperienced · Accounting/Finance · IT...,https://wuzzuf.net/jobs/p/g/jrvthu7qjoom-finan...
133,Trainee,Space42 -,"Dubai, United Arab Emirates",Full Time,Full TimeStudent · Accounting/Finance · Admini...,https://wuzzuf.net/jobs/p/g/zujy7cmgpqsi-train...
134,Security Engineer - Ubuntu,Canonical -,"Makkah, Saudi Arabia",Full Time,Full TimeEntry Level · Installation/Maintenanc...,https://wuzzuf.net/jobs/p/g/fhtjyqyuh4it-secur...

In [9]:
# Salary =[]
# for link in links:
#         client = urlopen(link)
#         html = client.read()
#         client.close()
#         soup = BeautifulSoup(src, 'html.parser')
#         salaries = soup.find_all('div', {'class':'css-rcl8e5'})
#         salary_text = salaries.find('span',{'class','css-47jx3m'})
#         salary.append(salary_text.text.strip())

In [ ]:
URL =links[0]
client = urlopen(URL)
html = client.read()
client.close()
soup1 = BeautifulSoup(html , 'html.parser')
soup1
salaries = soup1.find_all('div', {'class':'css-rcl8e5'})
# salary = salaries.find_all('span', {'class':'css-4xky9y'})
salaries